name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      confirm_apply:
        description: "Type APPLY to confirm Terraform apply"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  terraform-apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    if: ${{ inputs.confirm_apply == 'APPLY' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform apply
        run: terraform apply -input=false -auto-approve tfplan
